/* automatically generated by rust-bindgen */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Point {
    pub x: ::std::os::raw::c_int,
    pub y: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_Point() {
    assert_eq!(
        ::std::mem::size_of::<Point>(),
        8usize,
        concat!("Size of: ", stringify!(Point))
    );
    assert_eq!(
        ::std::mem::align_of::<Point>(),
        4usize,
        concat!("Alignment of ", stringify!(Point))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<Point>())).x as *const _ as usize },
        0usize,
        concat!("Offset of field: ", stringify!(Point), "::", stringify!(x))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<Point>())).y as *const _ as usize },
        4usize,
        concat!("Offset of field: ", stringify!(Point), "::", stringify!(y))
    );
}
extern "C" {
    pub fn manhattan(point: *mut Point) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn invert(point: *mut Point);
}
